#!/usr/bin/env python3

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
THEME_ROOT = REPO_ROOT / "src" / "runtime" / "builtin_theme"
OUTPUT_PATH = REPO_ROOT / "src" / "runtime" / "builtin_theme_embedded.mbt"


def moon_string_literal(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def const_name(prefix: str, relative_path: str) -> str:
    normalized = relative_path.replace("/", "_").replace(".", "_").replace("-", "_")
    return f"{prefix}_{normalized}".upper()


def collect_files(root: Path) -> list[str]:
    return sorted(
        str(path.relative_to(root)).replace("\\", "/")
        for path in root.rglob("*")
        if path.is_file()
    )


def emit_group(
    lines: list[str],
    fn_name: str,
    prefix: str,
    root: Path,
    relative_paths: list[str],
    key_prefix: str = "",
) -> None:
    for relative_path in relative_paths:
        const = const_name(prefix, relative_path)
        content = (root / relative_path).read_text(encoding="utf-8")
        lines.extend(
            [
                "///|",
                f"const {const} : String =",
                f"  {moon_string_literal(content)}",
                "",
            ]
        )
    lines.extend(
        [
            "///|",
            f"pub fn {fn_name}() -> Map[String, String] {{",
            "  let result : Map[String, String] = {}",
        ]
    )
    for relative_path in relative_paths:
        const = const_name(prefix, relative_path)
        lines.append(f'  result["{key_prefix}{relative_path}"] = {const}')
    lines.extend(["  result", "}", ""])


def main() -> None:
    if not THEME_ROOT.exists():
        raise SystemExit(f"missing builtin theme root: {THEME_ROOT}")

    layout_paths = collect_files(THEME_ROOT / "layouts")
    partial_paths = collect_files(THEME_ROOT / "partials")
    asset_paths = collect_files(THEME_ROOT / "assets")

    manifest_source = (THEME_ROOT / "theme.json").read_text(encoding="utf-8")
    legacy_layout_source = (THEME_ROOT / "layout.html").read_text(encoding="utf-8")

    lines = [
        "///|",
        "// Generated by scripts/generate_builtin_theme_bundle.py from src/runtime/builtin_theme.",
        "// Do not edit by hand.",
        "",
        "///|",
        "const BUILTIN_THEME_MANIFEST_SOURCE : String =",
        f"  {moon_string_literal(manifest_source)}",
        "",
        "///|",
        "pub fn built_in_theme_manifest_source() -> String {",
        "  BUILTIN_THEME_MANIFEST_SOURCE",
        "}",
        "",
        "///|",
        "const BUILTIN_THEME_LEGACY_LAYOUT_SOURCE : String =",
        f"  {moon_string_literal(legacy_layout_source)}",
        "",
        "///|",
        "pub fn built_in_theme_legacy_layout_source() -> String {",
        "  BUILTIN_THEME_LEGACY_LAYOUT_SOURCE",
        "}",
        "",
    ]

    emit_group(
        lines,
        "built_in_theme_layout_file_sources",
        "BUILTIN_THEME_LAYOUT",
        THEME_ROOT / "layouts",
        layout_paths,
        key_prefix="layouts/",
    )
    emit_group(
        lines,
        "built_in_theme_partial_file_sources",
        "BUILTIN_THEME_PARTIAL",
        THEME_ROOT / "partials",
        partial_paths,
        key_prefix="partials/",
    )
    emit_group(
        lines,
        "built_in_theme_asset_file_sources",
        "BUILTIN_THEME_ASSET",
        THEME_ROOT / "assets",
        asset_paths,
    )
    lines.extend(
        [
            "///|",
            "pub fn built_in_theme_asset_source(relative_path : String) -> String? {",
            "  built_in_theme_asset_file_sources().get(relative_path)",
            "}",
            "",
        ]
    )

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
